### PR TITLE
Fix pill flexbox alignment issues

### PR DESCRIPTION
**Pull request by gocemitevski**
This PR fixes several alignment and overflow issues with the dragable items in modern browsers and Internet Explorer.

Changes in this PR:

- no scrollbars should appear when dragging pills to the axes and the height of the container is larger for an instance when the pill is taken out of the container
- pills should be vertically aligned to center in the container, once its height is larger than the list of pills

Please test in both IE11 and all other modern browsers.

### CODE REVIEW

**Review by klikstermkd — CHANGES_REQUESTED** [review]
There is an issue when a pill contains text that is long, the pill overflows. Tested on Chrome.

Screenshot (2)

**Comment by gocemitevski** [comment]
@klikstermkd good catch.

**Comment by gocemitevski** [comment]
@klikstermkd please test again. Larger pills should be trimmed with ellipsis and the full name should be shown on hover from the title property.

**Review by klikstermkd — APPROVED** [review]
Works good.

**Pull request merged**
