### PR TITLE
Charts color picker in the Sysadmin settings

### PR DESCRIPTION
**Pull request by miroslavgruevski**

### CODE REVIEW

**Review by klikstermkd — COMMENTED** [review]
Code looks good, but maybe we should re-position the button for adding a new color?

@gocemitevski What do you think?

**Comment by klikstermkd** [comment]
Also, we can use the left sidebar to add some description for what each of the settings mean and how they can be used.

**Comment by miroslavgruevski** [comment]
> Code looks good, but maybe we should re-position the button for adding a new color?
> 
> @gocemitevski What do you think?

@klikstermkd @gocemitevski Maybe we could go with this position?

add color buton

**Comment by klikstermkd** [comment]
@miroslavgruevski Let's keep this PR open where I will work on the backend part to save the data. We can also iterate on the design.

_Note: The logic for managing SVG icons will be implemented in a new PR._

**Review by klikstermkd — APPROVED** [review]

**Pull request merged**
